import {COLOR} from './color';
export const customStepperStyles = {
  stepIndicatorSize: 25,
  currentStepIndicatorSize: 30,
  separatorStrokeWidth: 2,
  currentStepStrokeWidth: 3,
  stepStrokeCurrentColor: COLOR.YELLOW,
  stepStrokeWidth: 3,
  stepStrokeFinishedColor: COLOR.YELLOW,
  stepStrokeUnFinishedColor: '#aaaaaa',
  separatorFinishedColor: COLOR.YELLOW,
  separatorUnFinishedColor: '#aaaaaa',
  stepIndicatorFinishedColor: COLOR.YELLOW,
  stepIndicatorUnFinishedColor: '#ffffff',
  stepIndicatorCurrentColor: '#ffffff',
  stepIndicatorLabelFontSize: 13,
  currentStepIndicatorLabelFontSize: 13,
  stepIndicatorLabelCurrentColor: COLOR.YELLOW,
  stepIndicatorLabelFinishedColor: '#ffffff',
  stepIndicatorLabelUnFinishedColor: '#aaaaaa',
  labelColor: '#999999',
  labelSize: 13,
  currentStepLabelColor: COLOR.YELLOW,
};
