export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOG_OUT = 'LOG_OUT';

export const REGISTER_MERCHANT_REQUEST = 'REGISTER_MERCHANT_REQUEST';
export const REGISTER_MERCHANT_FAIL = 'REGISTER_MERCHANT_FAIL';
export const REGISTER_MERCHANT_SUCCESS = 'REGISTER_MERCHANT_SUCCESS';

export const REGISTER_BUYER_REQUEST = 'REGISTER_BUYER_REQUEST';
export const REGISTER_BUYER_FAIL = 'REGISTER_BUYER_FAIL';
export const REGISTER_BUYER_SUCCESS = 'REGISTER_BUYER_SUCCESS';

export const ACCOUNT_VERIFICATION_REQUEST = 'ACCOUNT_VERIFICATION_REQUEST';
export const ACCOUNT_VERIFICATION_FAIL = 'ACCOUNT_VERIFICATION_FAIL';
export const ACCOUNT_VERIFICATION_SUCCESS = 'ACCOUNT_VERIFICATION_SUCCESS';

export const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST';
export const EDIT_PROFILE_FAIL = 'EDIT_PROFILE_FAIL';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
