export const CREATE_ORDER = 'CREATE_ORDER';
export const GET_MERCHANT_PENDING_ORDERS = 'GET_MERCHANT_PENDING_ORDERS';
export const GET_MERCHANT_COMPLETED_ORDERS = 'GET_MERCHANT_COMPLETED_ORDERS';
export const GET_BUYER_PENDING_ORDERS = 'GET_BUYER_PENDING_ORDERS';
export const GET_BUYER_COMPLETED_ORDERS = 'GET_BUYER_COMPLETED_ORDERS';
export const UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS';
