export const GET_ALl_PRODUCTS_REQUEST = 'GET_ALl_PRODUCTS_REQUEST';
export const GET_ALL_PRODUCTS_FAILURE = 'GET_ALL_PRODUCTS_FAILURE';
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';

export const GET_YOUR_PRODUCTS_REQUEST = 'GET_YOUR_PRODUCTS_REQUEST';
export const GET_YOUR_PRODUCTS_FAILURE = 'GET_YOUR_PRODUCTS_FAILURE';
export const GET_YOUR_PRODUCTS_SUCCESS = 'GET_YOUR_PRODUCTS_SUCCESS';

export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';

export const EDIT_PRODUCT_REQUEST = 'EDIT_PRODUCT_REQUEST';
export const EDIT_PRODUCT_FAIL = 'EDIT_PRODUCT_FAIL';
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS';
