export const GET_ALl_STORES_REQUEST = 'GET_ALl_STORES_REQUEST';
export const GET_ALL_STORES_FAILURE = 'GET_ALL_STORES_FAILURE';
export const GET_ALL_STORES_SUCCESS = 'GET_ALL_STORES_SUCCESS';

export const GET_STORES_PRODUCTS_REQUEST = 'GET_STORES_PRODUCTS_REQUEST';
export const GET_STORES_PRODUCTS_FAILURE = 'GET_STORES_PRODUCTS_FAILURE';
export const GET_STORES_PRODUCTS_SUCCESS = 'GET_STORES_PRODUCTS_SUCCESS';

export const CREATE_STORE_REQUEST = 'CREATE_STORE_REQUEST';
export const CREATE_STORE_FAILURE = 'CREATE_STORE_FAILURE';
export const CREATE_STORE_SUCCESS = 'CREATE_STORE_SUCCESS';

export const GET_YOUR_STORES_REQUEST = 'GET_YOUR_STORES_REQUEST';
export const GET_YOUR_STORES_FAILURE = 'GET_YOUR_STORES_FAILURE';
export const GET_YOUR_STORES_SUCCESS = 'GET_YOUR_STORES_SUCCESS';

export const DELETE_STORE = 'DELETE_STORE';
export const STORE_ERROR = 'STORE_ERROR';

export const EDIT_STORE_REQUEST = 'EDIT_STORE_REQUEST';
export const EDIT_STORE_FAIL = 'EDIT_STORE_FAIL';
export const EDIT_STORE_SUCCESS = 'EDIT_STORE_SUCCESS';
